language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="mirage-http"
   - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
   - PINS="mirage-types:https://github.com/avsm/mirage.git#channel-result mirage-channel:https://github.com/avsm/mirage-channel.git#channel-result"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03.0
   - DISTRO=debian-testing OCAML_VERSION=4.03.0
   - DISTRO=debian-unstable OCAML_VERSION=4.03.0
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=centos-7 OCAML_VERSION=4.03.0
   - DISTRO=fedora-24 OCAML_VERSION=4.03.0
   - DISTRO=alpine OCAML_VERSION=4.04.0
